# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vietlott' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vietlott
  pod 'NotificationBannerSwift'
  pod 'Alamofire'
  pod 'Socket.IO-Client-Swift'

  target 'VietlottTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
